{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pnnlmiscscripts.chronyd.fullname" . }}
  labels:
    app: {{ template "pnnlmiscscripts.chronyd.name" . }}
    chart: {{ template "pnnlmiscscripts.chronyd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
